version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./config/php/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"

    volumes:
      - ./core/src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./config/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
