version: "3.9"
services:
  php:
    #restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: build/php/Dockerfile
    networks:
      intern:
        ipv4_address: 10.0.2.3
    volumes:
      - ./logs:/usr/src/backend/logs
      - ./core/sessions:/usr/src/backend/sessions
      - ./core/src/.:/usr/src/backend
      - /usr/src/backend/vendor
  nginx:
    #restart: always
    build:
      context: .
      dockerfile: build/nginx/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "4444:443"
    networks:
      intern:
        ipv4_address: 10.0.2.2
    volumes:
      - ./config/nginx:/etc/nginx
  mysql:
    container_name: djselect_mysql_1
    #restart: always
    image: "mariadb:10.11.6-jammy"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PW}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PW}"
    networks:
      intern:
        ipv4_address: 10.0.2.4
    volumes:
      - ./config/mariadb/script:/docker-entrypoint-initdb.d
      - ./config/mariadb/my.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql

networks:
  intern:
    name: "Internal network"
    ipam:
      driver: default
      config:
        - subnet: "10.0.2.0/24"
