version: "3.8"

services:
  core:
    build:
      context: .
      dockerfile: ./config/php/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./core/src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./config/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql

  ui:
    build:
      context: .
      dockerfile: ./config/react/Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8080/api
    ports:
      - "3000:80"
    volumes:
      - ./ui/app:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
